---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Dee.
--- DateTime: 2019/3/7 11:27
--- FIFO
---

queue = queue or {}

function queue.create()
    ---数据容器
    local data = {}
    ---数据长度
    local lenght = 0
    ---队首索引
    local first = 1

    ---获取队首值
    local peek = function()
        return data[first]
    end

    ---压入数据
    local enqueue = function(v)
        assert(v ~= nil, "nil value")
        lenght = lenght + 1
        table.insert(data, v)
    end

    ---弹出数据
    local dequeue = function()
        assert(lenght > 0, "nill queue")

        local ret = peek()
        data[first] = nil
        first = first+1
        lenght = lenght - 1
        return ret
    end

    local __tostring = function()
        return table.concat(data, ",")
    end

    local __index = function(i_t, key)
        if key == "len" then
            return lenght
        else
            return nil
        end
    end

    local __newindex = function(i_t, key, v)
        error(">> Dee: Limited access")
    end

    local __ipairs = function()
        error(">> Dee: Limited access")
    end

    local mt = {__tostring = __tostring, __index = __index, __newindex = __newindex, __ipairs = __ipairs, __pairs = __ipairs}

    local t = {
        enqueue = enqueue,
        dequeue = dequeue,
        peek = peek
    }

    setmetatable(t, mt)

    return t
end

return queue